<?php
namespace MyCompany\Service;

use MyCompany\Entity\User;
use Zend\ServiceManager\ServiceManager;
use Zend\Stdlib\ArrayUtils;
use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;
use MyCompany\Service\UserService;
use Doctrine\ORM\EntityManager;


class UserServiceTest extends AbstractHttpControllerTestCase
{

    protected $userService;

    protected $serviceManager;

    protected function getORM()
    {
        $orm = $this->serviceManager->get('doctrine.entitymanager.orm_default');
        return $orm;
    }


    protected function setUp()
    {

        // The module configuration should still be applicable for tests.
        // You can override configuration here with test case specific values,
        // such as sample view templates, path stacks, module_listener_options,
        // etc.
        $configOverrides = [];

        $this->setApplicationConfig(ArrayUtils::merge(
            include __DIR__ . '/../../../../config/application.config.php',
            $configOverrides
        ));

        parent::setUp();

        //$this->userService = new UserService();
        $this->serviceManager = $this->getApplicationServiceLocator();

    }



    protected function tearDown()
    {
        $orm = $this->getORM();
        $qb = $orm->createQueryBuilder();
        $exp = $qb->expr();
        $qb->select('u');
        $qb->from(User::class,'u');
        $qb->andWhere($exp->like('u.email', ':email'));
        $qb->setParameter('email','%ruslankus%');
        $iterateResult = $qb->getQuery();
        $res = $iterateResult->iterate();
        foreach ($res as $usAsArr){
            $orm->remove($usAsArr[0]);
        }
        $orm->flush();
        $orm->clear();


        parent::tearDown(); // TODO: Change the autogenerated stub
    }



    public function test__construct()
    {
        $userService = $this->serviceManager->get(UserService::class);
        $this->assertInstanceOf(UserService::class,$userService);
    }


    public function testRegisterUser()
    {
        $email = 'ruslankus@yahoo.com';
        $password = 'abc1234';
        $userService = $this->serviceManager->get(UserService::class);

        $userObj = $userService->registerUser($email,$password);
        $this->assertInstanceOf(User::class,$userObj);
    }


    public function testRegisterUserMailAlreadyExistsException()
    {
        $email = 'ruslankus@yahoo.com';
        $password = 'abc1234';
        $userService = $this->serviceManager->get(UserService::class);
        $userObj = $userService->registerUser($email,$password);

        $this->assertInstanceOf(User::class,$userObj);

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage(UserService::ERROR_USER_EXIST_MSG);
        $userObj = $userService->registerUser($email,$password);

    }










}