version: '2'
services:
  mysql-api:
      image: mariadb
      ports:
          - "3306:3306"
      volumes:
          - "./.data/db:/var/lib/mysql:rw"
      restart: always
      environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: mysql
  api:
      build: .
      image: api
      environment:
          XDEBUG_CONFIG: remote_host=192.168.1.174
      depends_on:
        - mysql-api
      ports:
          - "80:80"
      links:
          - mysql-api:mysql-api
      volumes:
          - "../:/var/www/site"
      restart: always