<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace MyCompany;


use MyCompany\Factory\UserServiceFactory;
use DoctrineORMModule\Service\EntityManagerFactory;
use MyCompany\Service\UserService;
use Zend\ModuleManager\Feature\ServiceProviderInterface;

class Module implements ServiceProviderInterface
{

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/../config/module.config.php';
    }



    /**
     * Expected to return \Zend\ServiceManager\Config object or array to
     * seed such an object.
     *
     * @return array|\Zend\ServiceManager\Config
     */
    public function getServiceConfig()
    {
        return [
            'factories' => [
                UserService::class => UserServiceFactory::class
            ]
        ];
    }


}