<?php $obj = $this ?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Reset password</title>
<?php


    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

    echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')])
        ->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
        ->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));

    echo $this->headScript()
        ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
        ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));
?>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="console alert alert-warning hidden">

        </div><!--console -->

        <form class="form-horizontal" id="reset-password-form" >

            <input type="hidden" name="token" value="" >
            <input type="hidden" name="email" value="" >

            <fieldset>
                <legend>Password reset</legend>


                <div class="form-group">
                    <label class="col-md-4 control-label" for="password1">
                        New password
                    </label>

                    <div class="col-md-4">
                        <input id="password1" name="newPassword" type="password"
                               placeholder="Your new password" class="form-control input-md" required="">
                        <span class="help-block">Must be at least 5 characters long</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="password2">
                        New password(Reapeat)
                    </label>

                    <div class="col-md-4">
                        <input id="password2" name="newPassword" type="password"
                               placeholder="Your new password(again)" class="form-control input-md" required="">
                        <span class="help-block">Same as above</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="submit">

                    </label>
                    <div class="col-md-4">
                        <button id="submit" name="submit" class="btn btn-primary">
                            Update my password
                        </button>
                    </div>
                </div>


            </fieldset>

        </form>


    </div>
</div>

</body>
</html>